import img1 from "../assets/images/products/newArrival/black berry.png"
import img2 from "../assets/images/products/newArrival/black cardamon.png"
import img3 from "../assets/images/products/newArrival/black papper.png"
import img4 from "../assets/images/products/newArrival/black papper.png"
import img5 from "../assets/images/products/newArrival/cloves.png"
import spfOne from "../assets/images/products/newArrival/nutmace.png"
export const baseURL = "http://192.168.29.80:8000/";
// export const baseURL = "https://vyavaharapp.com/freshbells/api";
// export const  baseURL= 'https://a2zserver.in/Freshbells/api/';
// export const BASEURL= 'https://a2zserver.in/Freshbells/';
export const data = [{
  _id: 1001,
  img: spfOne,
  productName: "Garlic",
  price: "350.00",
  offerPrice: "300.00",
  stock: 10, 
  quantity:[250,500], 
  badge: true,
  des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
},
{
  _id: 1002,
  img: img5,
  productName: "Cloves",
  price: "180.00",
  offerPrice: "130.00",
  stock: 0,
  quantity:[250,500],
  badge: true,
  des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
},
{
  _id: 1003,
  img: img1,
  productName: "Black berry",
  price: "250.00",
  offerPrice: "200.00",
  stock: 0,
  quantity:[250,500],
  badge: true,
  des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
},
{
  _id: 1004,
  img: img4,
  productName: "Cinamon",
  price: "520.00",
  offerPrice: "300.00",
  stock: 5,
  quantity:[250,500],
  badge: true,
  des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
},
{
  _id: 1005,
  img: img3,
  productName: "Garlic",
  price: "435.00",
  stock: 30,
  quantity:[250,500],
  offerPrice: "300.00",
  badge: false,
  des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
},
{
  _id: 1006,
  img: img2,
  productName: "Black cardamon",
  price: "180.00",
  stock: 50,
  quantity:[250,500],
  offerPrice: "300.00",
  badge: false,
  des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
},
{
  _id: 1007,
  img: spfOne,
  productName: "Millets",
  price: "350.00",
  offerPrice: "300.00",
  stock: 10,
  quantity:[250,500],
  badge: true,
  des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
},
{
  _id: 1008,
  img: img5,
  productName: "Millets",
  price: "180.00",
  offerPrice: "130.00",
  stock: 0,
  quantity:[250,500],
  badge: true,
  des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
},
{
  _id: 1009,
  img: img1,
  productName: "Millets",
  price: "250.00",
  offerPrice: "200.00",
  stock: 0,
  quantity:[250,500],
  badge: true,
  des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
},
{
  _id: 1010,
  img: spfOne,
  productName: "Millets",
  price: "350.00",
  offerPrice: "300.00",
  stock: 10,
  quantity:[250,500],
  badge: true,
  des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
}]
